baseURL = "/"
languageCode = "en-us"
title = "Pia Smith Web Portfolio"
author = "Pia Smith"
theme = "blackburn"


[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "design, development and data"
  brand = "/"
  googleAnalytics = "Your Google Analytics tracking ID"
  # CSS name for highlight.js
  highlightjs = "androidstudio"

  custom_css = ["css/styles.css"]
  custom_js = ["js/main.js", "https://www.gstatic.com/firebasejs/5.6.0/firebase.js"]
  
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Portfolio"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-file-text fa-fw'></i>"
    weight = 2
    identifier = "resume"
    url = "/resume/"

  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    identifier = "contact"
    url = "/contact/"
  
    [[menu.main]]
    name = "365 Challenge"
    identifier = "365"
    pre = "<i class='fa fa-mobile fa-fw'></i>"
    weight = 4
    url = "/365/"
  

    [social]
  # SNS microblogging
  twitter = "pia_smith"

  # SNS career oriented
  linkedin = "piasmith101"

  # Techie
  github = "basiccreation"

